[workspace]
members = ["core", "proc", "alkahest", "benchmark"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
alkahest-core = { path = "core" }
alkahest-parse = { path = "parse" }
alkahest-proc = { path = "proc" }

unicode-ident = "1.0.24"
quote = "1.0.47"
proc-macro2 = "1.0.107"
rand = "0.10.2"
basic-lexer = { path = "../basic-lexer" }
