[package]
name = "alkahest"
version.workspace = true
edition.workspace = true

[dependencies]
alkahest-core = { workspace = true }
alkahest-proc = { workspace = true, optional = true }
rand.workspace = true

[dev-dependencies]
rand.workspace = true

[features]
proc = ["dep:alkahest-proc"]
alloc = ["alkahest-core/alloc"]
std = ["alkahest-core/std"]
default = ["std"]

[[example]]
name = "new"
path = "examples/new.rs"
required-features = ["proc"]

[[example]]
name = "test"
path = "examples/test.rs"
required-features = ["proc"]

[[example]]
name = "bench"
path = "examples/bench.rs"
required-features = ["proc"]
