name: Check multiple platforms

on:
  pull_request:
    types: [ opened, edited ]
    paths:
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  check-targets:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Run cargo check
      run: cargo check --all --features=bincoded,derive
