name: Check multiple toolchains

on:
  pull_request:
    types: [ opened, edited ]
    paths:
      - '**.rs'
      - '**/Cargo.toml'

env:
  CARGO_TERM_COLOR: always

jobs:
  check-toolchains:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-toolchain: [stable, nightly]
    steps:
    - uses: actions/checkout@v4
    - name: Install ${{ matrix.rust-toolchain }} toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.rust-toolchain }}
    - name: Run cargo check
      run: cargo check --all --features=bincoded,derive
